name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build rosbot-base image (local build)
      - name: Build rosbot-base image
        run: |
          docker buildx build --platform linux/${{ matrix.architecture }} -t rosbot-base:latest ./docker/base --load

      # Cache Docker package image
      - name: Cache Docker package image
        id: package_cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: package-${{ matrix.architecture }}-${{ github.sha }}
          restore-keys: |
            package-${{ matrix.architecture }}-
      
      # Build rosbot-packages image using the locally built rosbot-base image
      - name: Build rosbot-packages image
        run: |
          docker buildx build --platform linux/${{ matrix.architecture }} -t rosbot-packages:latest ./docker/package --build-arg ARCH=${{ matrix.architecture }} --load

      # Cache Docker source image
      - name: Cache Docker source image
        id: source_cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: source-${{ matrix.architecture }}-${{ github.sha }}
          restore-keys: |
            source-${{ matrix.architecture }}-
      
      # Build rosbot-local image using the locally built rosbot-packages image
      - name: Build rosbot-local image
        run: |
          docker buildx build --platform linux/${{ matrix.architecture }} -t rosbot-local:latest ./docker/source --build-arg ARCH=${{ matrix.architecture }} --load

      # Save source code image as artifact (if needed)
      - name: Save rosbot-local image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: rosbot-local-image-${{ matrix.architecture }}
          path: ./docker/source/*.tar
