name: Build ROS2 Image for Jetson and AMD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [arm64, amd64]  # Define the architectures you want to support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for ARM Emulation (if using ARM architecture)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Build base image for ${{ matrix.arch }}
        run: |
          docker build \
            --build-arg ARCH=${{ matrix.arch }} \
            -t rosbot-base:${{ matrix.arch }}:latest \
            -f docker/Dockerfile.base .

      - name: Build the package image for ${{ matrix.arch }}
        run: |
          docker build \
            --build-arg ARCH=${{ matrix.arch }} \
            -t rosbot-packages:${{ matrix.arch }}:latest \
            -f docker/Dockerfile.packages .

      # Package the local image and save it as a tarfile for each architecture
      - name: Package local image for ${{ matrix.arch }}
        run: |
          docker save rosbot-local:${{ matrix.arch }}:latest -o rosbot-local-${{ matrix.arch }}.tar

      # Optionally upload the tarfile to the repository for each architecture
      - name: Upload Docker image artifact for ${{ matrix.arch }}
        uses: actions/upload-artifact@v3
        with:
          name: rosbot-local-image-${{ matrix.arch }}
          path: rosbot-local-${{ matrix.arch }}.tar
