name: Build Docker Images and Upload Artifact

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build base image
      - name: Build base image
        run: |
          docker build -t rosbot-base:latest -f docker/Dockerfile.base .

      # Step 4: Build packages image
      - name: Build packages image
        run: |
          docker build -t rosbot-packages:latest -f docker/Dockerfile.packages .

      # Step 5: Build local image
      - name: Build local image
        run: |
          docker build -t rosbot-local:latest -f docker/Dockerfile.local .

      # Step 6: Save local image as tarball
      - name: Save rosbot-local image as tarball
        run: |
          docker save rosbot-local:latest -o rosbot-local.tar

      # Step 7: Upload rosbot-local tarball as an artifact
      - name: Upload rosbot-local.tar as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: rosbot-local
          path: rosbot-local.tar
